export type {
  BackButton,
  BiometricManager,
  BiometryInfo,
  ChatType,
  CodeReaderResponse,
  ContactResponse,
  DeviceStorage,
  DownloadFileResponse,
  HapticFeedback,
  ImpactStyle,
  MaxBridge,
  MaxBridgeErrorShape,
  MaxBridgeEventMap,
  MaxBridgeEventName,
  MaxBridgeInfo,
  MaxBridgeScriptProps,
  MaxChat,
  MaxInitData,
  MaxPlatform,
  MaxTransportKind,
  MaxUser,
  NotificationType,
  ScreenBrightnessResponse,
  ScreenCapture,
  ScreenCaptureResponse,
  SecureStorage,
  ShareMaxContentParams,
  ShareMediaParams,
  ShareTextParams,
  StorageValueResponse,
  SwipesBehaviorResponse,
} from "./types"

export {
  bootstrapMaxBridge,
  close,
  createBridgeError,
  disableClosingConfirmation,
  disableScreenCaptureProtection,
  disableVerticalSwipes,
  downloadFile,
  enableClosingConfirmation,
  enableScreenCaptureProtection,
  enableVerticalSwipes,
  ensureMaxBridge,
  getBiometricManager,
  getChat,
  getDeviceStorage,
  getInitData,
  getInitDataUnsafe,
  getMaxBridge,
  getMaxBridgeSnapshot,
  getPlatform,
  getQueryId,
  getSecureStorage,
  getUser,
  getVersion,
  getWebApp,
  hapticImpact,
  hapticNotification,
  hapticSelectionChanged,
  isBridgeError,
  isMaxBridgeAvailable,
  isScreenCaptureProtected,
  markMaxBridgeLoaded,
  offEvent,
  onEvent,
  openCodeReader,
  openLink,
  openMaxLink,
  ready,
  requestContact,
  requestMaxBrightness,
  restoreBrightness,
  shareContent,
  shareMaxContent,
  subscribeToMaxBridge,
  supportsMaxFeature,
} from "./bridge"

export {
  CODE_READER_TIMEOUT_MS,
  compareVersions,
  createRequestId,
  extractParamFromHashes,
  getErrorCode,
  getHashParam,
  INIT_DATA_KEY,
  INTERACTIVE_REQUEST_TIMEOUT_MS,
  isVersionAtLeast,
  parseInitData,
  PLATFORM_KEY,
  REQUEST_TIMEOUT_MS,
  VERSION_KEY,
} from "./helpers"

export {
  useBackButton,
  useClosingConfirmation,
  useHaptic,
  useMaxBridge,
  useMaxBridgeBootstrap,
  useMaxEvent,
  useMaxReady,
  usePhoneRequest,
  useQrReader,
} from "./hooks"

export { MaxBridgeScript } from "./max-bridge-script"
export { MaxBridgeProvider } from "./provider"
